const categories = [
  {
    id: 1,
    name: "Biryani",
    image: "img/Biryani.jpg",
    category: "Dinner",
    price: 399,
  },
  {
    id: 2,
    name: "Chicken Noodles",
    image: "Images/chinoodles.jpg",
    price: 499,
  },
  {
    id: 3,
    name: "Burger",
    image: "Images/Burger.jpg",
    price: 599,
  },

  {
    id: 4,
    name: "Desert",
    image: "Images/Desert.jpg",
    price: 299,
  },
  {
    id: 5,
    name: "Chicken Wings",
    image: "Images/Chicken Wings.jpg",
    price: 399,
  },
  {
    id: 6,
    name: "Moarella_Sticks",
    image: "Images/Moaaarella_Sticks.jpg",
    price: 499,
  },
  {
    id: 7,
    name: "Soup",
    image: "Images/Soup.jpg",
    price: 499,
  },
  {
    id: 8,
    name: "Hydrabadi Biryani",
    image: "Images/hydrabadi.jpg",
    category: "Dinner",
    price: 499,
  },
  {
    id: 9,
    name: "Chicken Rice",
    image: "Images/r1.png",
    category: "Dinner",
    price: 499,
  },
  {
    id: 9,
    name: "Mutton Rice",
    image: "Images/r2.png",
    category: "Dinner",
    price: 499,
  },
  {
    id: 10,
    name: "Indian Rice",
    image: "Images/r3.png",
    category: "Dinner",
    price: 499,
  },
  {
    id: 11,
    name: "Veg Biryani",
    image: "Images/hydrabadi.jpg",
    category: "Dinner",
    price: 499,
  },
  {
    id: 12,
    name: "Hydrabadi Biryani",
    image: "Images/hydrabadi.jpg",
    category: "Dinner",
    price: 499,
  },
  {
    id: 13,
    name: "Fish Chawal",
    image: "Images/fi1.png",
    category: "Lunch",
    price: 499,
  },
  {
    id: 14,
    name: "Hydrabadi Fish",
    image: "Images/fi2.png",
    category: "Lunch",
    price: 499,
  },
  {
    id: 15,
    name: "Fish Curry",
    image: "Images/fi3.png",
    category: "Lunch",
    price: 499,
  },
  {
    id: 16,
    name: "Fish Kadai",
    image: "Images/fi4.png",
    category: "Lunch",
    price: 499,
  },
  {
    id: 17,
    name: "Fish Pulaw",
    image: "Images/fi5.png",
    category: "Dinner",
    price: 499,
  },
  {
    id: 18,
    name: "Icecream Strawberry",
    image: "Images/i5.png",
    category: "Dinner",
    price: 499,
  },
  {
    id: 19,
    name: "Icecream Buttter Scotch",
    image: "Images/i4.png",
    category: "Dinner",
    price: 499,
  },
  {
    id: 20,
    name: "IceCream shake",
    image: "Images/i3.png",
    category: "icecream",
    price: 499,
  },
  {
    id: 21,
    name: "Icecream Chocolate",
    image: "Images/i2.png",
    category: "icecream",
    price: 499,
  },
  {
    id: 22,
    name: "Icecream Vanilla",
    image: "Images/i1.png",
    category: "icecream",
    price: 499,
  },
  {
    id: 23,
    name: "Icecream Vanilla",
    image: "Images/Image-8.png",
    category: "Food",
    price: 499,
  },
];
export default categories;
